import type { Metadata } from "next";
import { Chango, Outfit } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Navbar from "@/components/common/Navbars/Navbar";

const kanitFont = Outfit({
  variable: "--font-Outfit",
  // subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const LogoFont = Chango({
  variable: "--font-logo",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Zappy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanitFont.variable} ${kanitFont.className} ${LogoFont.variable} bg-app-secondary`}
      >
        <Navbar />
        <div className="app-width">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
