import type { Metadata } from "next";
import { Chango, Outfit } from "next/font/google";
import React from "react";
import { Toaster } from "sonner";
import "./globals.css";
import ReactQueryProvider from "./provider";

const OutfitFont = Outfit({
  variable: "--font-Outfit",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const ChangoFont = Chango({
  variable: "--font-logo",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "chatnX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OutfitFont.variable} ${OutfitFont.className} ${ChangoFont.variable} bg-app-secondary`}
      >
        <ReactQueryProvider>
          <div>{children}</div>
          <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
